sonar.projectKey=internxt_mail
sonar.organization=internxt

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# This parameter must be set to the path of the report file produced by your coverage tool. The path can be either absolute or relative to the project root.
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
# Coverage exclusions:
sonar.coverage.exclusions=\
  **/*.spec.ts, \
  **/*.e2e-spec.ts, \
  **/*.module.ts, \
  **/test/**
sonar.cpd.exclusions=**/*.spec.ts, **/*.e2e-spec.ts
