replicaCount: 2

image:
  repository: internxt/mail-server
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: LoadBalancer
  port: 3100

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeEnv: production

paymentsApiUrl: 'https://gateway.internxt.com/payments'

redisUrl: REPLACE_ME

database:
  host: REPLACE_ME
  port: '5432'
  name: REPLACE_ME
  username: REPLACE_ME

stalwart:
  jmapUrl: http://stalwart:8080
  adminUrl: http://stalwart:8080
  smtpHost: stalwart
  smtpPort: 465

mta:
  hooksUsername: stalwart

secretName: mail-server-secrets

probes:
  liveness:
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
