replicaCount: 1

image:
  repository: stalwartlabs/stalwart
  tag: v0.16.4
  pullPolicy: IfNotPresent

role: ''

pushShard: ''

recoveryMode:
  enabled: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: mail-ingress-traefik
  clusterIssuer: letsencrypt-prod
  host: mail.inxt.me
  tlsSecretName: stalwart-tls

mailService:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    management:
      port: 8080
      nodePort: 30742
    smtp:
      port: 25
      nodePort: 32443
    smtps:
      port: 465
      nodePort: 32010
    submission:
      port: 587
      nodePort: 32303
    imap:
      port: 143
      nodePort: 30164
    imaps:
      port: 993
      nodePort: 30110
    pop3:
      port: 110
      nodePort: 31940
    pop3s:
      port: 995
      nodePort: 31666
    managesieve:
      port: 4190
      nodePort: 32309

persistence:
  enabled: true
  size: 5Gi
  storageClass: ''

resources:
  requests:
    cpu: 250m
    memory: 512Mi
    ephemeral-storage: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
    ephemeral-storage: 1Gi

dataStore:
  '@type': PostgreSql
  host: REPLACE_ME
  port: 5432
  database: REPLACE_ME
  authUsername: REPLACE_ME
  authSecret:
    '@type': EnvironmentVariable
    variableName: STALWART_DB_PASSWORD
  useTls: true
  allowInvalidCerts: true

secretName: stalwart-secrets
