replicaCount: 1

image:
  repository: stalwartlabs/stalwart
  tag: v0.16.4
  pullPolicy: IfNotPresent

role: ''

pushShard: ''

recoveryMode:
  enabled: false

service:
  type: LoadBalancer
  ports:
    management: 8080
    http: 80
    https: 443
    smtp: 25
    smtps: 465
    submission: 587
    imap: 143
    imaps: 993
    pop3: 110
    pop3s: 995
    managesieve: 4190

persistence:
  enabled: true
  size: 5Gi
  storageClass: ''

resources:
  requests:
    cpu: 250m
    memory: 512Mi
    ephemeral-storage: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
    ephemeral-storage: 1Gi

dataStore:
  '@type': PostgreSql
  host: REPLACE_ME
  port: 5432
  database: REPLACE_ME
  authUsername: REPLACE_ME
  authSecret:
    '@type': EnvironmentVariable
    variableName: STALWART_DB_PASSWORD
  useTls: true
  allowInvalidCerts: true

secretName: stalwart-secrets
