{{- if .Values.ingress.enabled }}
{{- $mtaStsHosts := .Values.ingress.mtaStsHosts | default list }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stalwart-ingress
  labels:
    app: stalwart
    owner: internxt
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stalwart
                port:
                  number: {{ .Values.service.port }}
    {{- range $mtaStsHosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /.well-known/mta-sts.txt
            pathType: Exact
            backend:
              service:
                name: stalwart
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
        {{- range $mtaStsHosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
