apiVersion: v1
kind: Service
metadata:
  name: stalwart
  labels:
    app: stalwart
    owner: internxt
spec:
  type: {{ .Values.service.type }}
  selector:
    app: stalwart
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: management
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: stalwart-nodeport
  labels:
    app: stalwart
    owner: internxt
spec:
  type: {{ .Values.mailService.type }}
  {{- with .Values.mailService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  selector:
    app: stalwart
  ports:
    {{- range $name, $cfg := .Values.mailService.ports }}
    - name: {{ $name }}
      port: {{ $cfg.port }}
      targetPort: {{ $name }}
      nodePort: {{ $cfg.nodePort }}
      protocol: TCP
    {{- end }}
